package com.wiser.mframe.db.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.wiser.mframe.db.dao.TestModel;

import com.wiser.mframe.db.dao.TestModelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig testModelDaoConfig;

    private final TestModelDao testModelDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        testModelDaoConfig = daoConfigMap.get(TestModelDao.class).clone();
        testModelDaoConfig.initIdentityScope(type);

        testModelDao = new TestModelDao(testModelDaoConfig, this);

        registerDao(TestModel.class, testModelDao);
    }
    
    public void clear() {
        testModelDaoConfig.clearIdentityScope();
    }

    public TestModelDao getTestModelDao() {
        return testModelDao;
    }

}
