package com.wiser.mframe.db.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TEST_MODEL".
*/
public class TestModelDao extends AbstractDao<TestModel, Long> {

    public static final String TABLENAME = "TEST_MODEL";

    /**
     * Properties of entity TestModel.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Test1 = new Property(1, String.class, "test1", false, "TEST1");
        public final static Property Test2 = new Property(2, int.class, "test2", false, "TEST2");
    }


    public TestModelDao(DaoConfig config) {
        super(config);
    }
    
    public TestModelDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TEST_MODEL\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"TEST1\" TEXT," + // 1: test1
                "\"TEST2\" INTEGER NOT NULL );"); // 2: test2
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TEST_MODEL\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, TestModel entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String test1 = entity.getTest1();
        if (test1 != null) {
            stmt.bindString(2, test1);
        }
        stmt.bindLong(3, entity.getTest2());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, TestModel entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String test1 = entity.getTest1();
        if (test1 != null) {
            stmt.bindString(2, test1);
        }
        stmt.bindLong(3, entity.getTest2());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public TestModel readEntity(Cursor cursor, int offset) {
        TestModel entity = new TestModel( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // test1
            cursor.getInt(offset + 2) // test2
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, TestModel entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTest1(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setTest2(cursor.getInt(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(TestModel entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(TestModel entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(TestModel entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
